version: '3'
services:
  jenkins:
    container_name: jenkins-container
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins-home:/var/jenkins_home"
    networks:
      - net
networks:
  net:
